### Create an order
POST http://localhost:3000/api/v1/orders
Content-Type: application/json

{
  "userId": "69211195380a8797064535de",   
  "products": ["77abc123def4567890"], 
  "quantity": 1,
  "totalPrice": 250.00,
  "status": "pending",
  "shopId": "691f8a71874fa3f5d2b7ce6c"
}

### Get all orders
GET http://localhost:3000/api/v1/orders

### Get order by ID
GET http://localhost:3000/api/v1/orders/691d01eee786e612c3599a6e
### Update order
PUT http://localhost:3000/api/v1/orders/691d01eee786e612c3599a6e
Content-Type: application/json

{
  "status": "shipped"
}

### Delete order
DELETE http://localhost:3000/api/v1/orders/691d01eee786e612c3599a6e
