### Create an order
POST http://localhost:3000/api/v1/orders
Content-Type: application/json

{
  "userId": "j",
  "products": ["Ergo Chair X", "Desk Lamp"],
  "quantity": 2,
  "totalPrice": 499.98,
  "status": "pending",
  "shopId": "653a1f2e9c8b4a1d2f4e5678"
}

### Get all orders
GET http://localhost:3000/api/v1/orders

### Get order by ID
GET http://localhost:3000/api/v1/orders/691d01eee786e612c3599a6e
### Update order
PUT http://localhost:3000/api/v1/orders/691d01eee786e612c3599a6e
Content-Type: application/json

{
  "status": "shipped"
}

### Delete order
DELETE http://localhost:3000/api/v1/orders/691d01eee786e612c3599a6e
