### Create a product
POST http://localhost:3000/api/v1/products
Content-Type: application/json

{ 
  "name": "Chair",
  "price": 60,
  "category": ["kitchen"],
  "shopId": "691f8a71874fa3f5d2b7ce6c",
  "description": "Kitchen chair"

}

### Get all products
GET http://localhost:3000/api/v1/products

### Get product by ID
GET http://localhost:3000/api/v1/products/691c768c834cced67a92acc1

### Update product
PUT http://localhost:3000/api/v1/products/691c768c834cced67a92acc1
Content-Type: application/json

{
  "price": 269.99,
  "description": "Updated description"
}

### Delete product
DELETE http://localhost:3000/api/v1/products/6921a25b77747c9dace05592
