### Create a new shop
POST http://localhost:3000/api/v1/shops
Content-Type: application/json

{
   "name": "Tech Haven Electronics",
  "slogan": "Your home for smart living",
  "ownerId": "69211195380a8797064535d7",
  "logo": "tech-haven-logo.png",
  "title": "Tech Haven",
  "favIcon": "tech-haven-favicon.ico",
  "heroImage": "https://images.unsplash.com/photo-1518770660439-4636190af475",
  "currency": "EUR"
}



### Get all shops
GET http://localhost:3000/api/v1/shops

### Get shop by ID
GET http://localhost:3000/api/v1/shops/6904a8c71bc6767f0f4270c0

### Update shop
PUT http://localhost:3000/api/v1/shops/691f8a71874fa3f5d2b7ce6c
Content-Type: application/json

{
    "ownerId": "691f8a71874fa3f5d2b7ce6c"

}

### Delete shop
DELETE http://localhost:3000/api/v1/shops/690bee2b77a0cac0fb8226c9
