### Create a new shop
POST http://localhost:3000/api/v1/shops
Content-Type: application/json

{
  "name": "3D Express Store",
  "address": "42 Maker Street, Dublin",
  "phoneNumber": "+353861234890",
  "description": "Specialist in 3D printing gear and accessories"
}


### Get all shops
GET http://localhost:3000/api/v1/shops

### Get shop by ID
GET http://localhost:3000/api/v1/shops/6904a8c71bc6767f0f4270c0

### Update shop
PUT http://localhost:3000/api/v1/shops/690bee2b77a0cac0fb8226c9
Content-Type: application/json

{
  "slogan": "slogan",
  "title": "Updated Shop Title"
}

### Delete shop
DELETE http://localhost:3000/api/v1/shops/690bee2b77a0cac0fb8226c9
