### Create a new user
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "fullName": "Patrick Doyle",
  "email": "patrick.doyle@example.com",
  "passwordHash": "hashedpassword444",
  "address": "33 High Street, Limerick",
  "phoneNumber": "+353871234574",
  "shopId": "691f8a71874fa3f5d2b7ce6c",
  "role": "customer"
}


### Get all users
GET http://localhost:3000/api/v1/users

### Get user by ID
GET http://localhost:3000/api/v1/users/690bedb077a0cac0fb8226c7

### Update user
PUT http://localhost:3000/api/v1/users/69211195380a8797064535d7
Content-Type: application/json

{
    "role": "admin"
}

### Delete user
DELETE http://localhost:3000/api/v1/users/690bedb077a0cac0fb8226c7
