### Create a new user
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "fullName": "Oluwole Dev",
  "email": "oluwole@example.com",
  "passwordHash": "hashed_pw_123",
  "address": "Dublin",
  "phoneNumber": "+353123456789",
  "shopId": "shop123",
  "role": "shop"
}

### Get all users
GET http://localhost:3000/api/v1/users

### Get user by ID
GET http://localhost:3000/api/v1/users/6904acb008932f9d319f7ab3

### Update user
PUT http://localhost:3000/api/v1/users/6904a8981bc6767f0f4270c2
Content-Type: application/json

{
  "address": "sligo",
  "phoneNumber": "+353987654321"
}

### Delete user
DELETE http://localhost:3000/api/v1/users/6904a8981bc6767f0f4270c2
